apiVersion: v1
kind: Namespace
metadata:
  name: transformer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: fluent-transformer-deployment
  namespace: transformer
spec:
  replicas: 3
  selector:
    matchLabels:
      app: fluent-transformer
  template:
    metadata:
      labels:
        app: fluent-transformer
    spec:
      automountServiceAccountToken: false
      containers:
      - name: fluent-transformer
        image: fluent-transformer:local
        ports:
        - containerPort: 8081
          name: default
        env:
        - name: ASPNETCORE_ENVIRONMENT
          value: "Development"
        resources:
          limits:
            memory: 1000Mi
            cpu: 500m
---
apiVersion: v1
kind: Service
metadata:
  name: fluent-transformer-service
  namespace: transformer
spec:
  type: LoadBalancer
  ports:
  - port: 8081
    targetPort: 8081
  selector:
    app: fluent-transformer